name: Build gettext
on:
  workflow_dispatch:
    inputs:
      version:
        description: gettext tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
      stability:
        description: the series stability
        required: false
        default: 'staging'
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [arm64]
    runs-on: ARM64
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout gettext
        uses: actions/checkout@v4
        with:
          path: gettext
          repository: php-win-ext/gettext
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore from cache and install vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: false
          vcpkgDirectory: '${{ github.workspace }}/gettext/vcpkg'
          vcpkgGitCommitId: '8eb57355a4ffb410a2e94c07b4dca2dffbee8e50'
          vcpkgTriplet: ${{ matrix.arch }}-windows
          vcpkgArguments: 'gettext'
          additionalCachedPaths: '${{ github.workspace }}/build/vcpkg_installed'
      - name: Build gettext
        run: cd gettext\MSVC${{steps.virtuals.outputs.vsnum}} && msbuild gettext.sln /p:Configuration=Release /p:Platform=${{steps.virtuals.outputs.msarch}} /p:PlatformToolset=${{steps.virtuals.outputs.msts}} /p:WindowsTargetPlatformVersion=${{steps.virtuals.outputs.winsdk}}
      - name: Install gettext
        run: |
          cd gettext\MSVC${{steps.virtuals.outputs.vsnum}}
          if "${{matrix.arch}}" == "x64" (
              set release_out=x64\Release
              set libintl_lib_out=libintl_dll\x64\Release\libintl.lib
          ) if "${{matrix.arch}}" == "arm64" (
              set release_out=arm64\Release
              set libintl_lib_out=libintl_dll\arm64\Release\libintl.lib
          ) else (
              set release_out=Release
              set libintl_lib_out=Release\libintl.lib
          )
          xcopy libintl_dll\%release_out%\libintl.dll ..\..\install\bin\*
          xcopy libintl_dll\%release_out%\libintl.pdb ..\..\install\bin\*
          xcopy ..\source\gettext-runtime\intl\libgnuintl.h ..\..\install\include\*
          rename ..\..\install\include\libgnuintl.h libintl.h
          xcopy %libintl_lib_out% ..\..\install\lib\*
          xcopy libintl_static\%release_out%\libintl_a.lib ..\..\install\lib\*
          xcopy libintl_static\%release_out%\libintl_a.pdb ..\..\install\lib\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: install
